### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by marloncarvalho** [mcrisc/porextenso#1]
@mcrisc Fiz um fork do seu projeto com o objetivo de atualizá-lo para usar a nova Money API. Contudo, como a estrutura do seu projeto é bem diferente, acabei fazendo um projeto diferente. Ele se encontra em https://github.com/marloncarvalho/dinheirama. 

Observe que copiei sua classe e fiz todas as devidas referências ao seu projeto. Você pode ver essas referências no README e nas próprias classes do projeto. Parabéns pela implementação, ficou sucesso!

**Comment by mcrisc** [comment]
Saudações, @marloncarvalho! Essa implementação já tem alguns anos. Ainda não existia Money API naquela época. Tem algumas coisas que eu queria ter melhorado, mas fui deixando, deixando... :-)

Fico feliz que o projeto esteja sendo útil! Se encontrar algum erro, pode abrir um "issue" aqui que eu terei prazer em corrigir.
