### ISSUE TITLE
MIT é uma licença de código aberto, e NÃO de código livre.

### ISSUE THREAD

**Issue by emanuelmoraes-dev** [mcrisc/porextenso#3]

**Comment by mcrisc** [comment]
De acordo com a FSF, a MIT, ou mais especificamente X11 License, é uma licença de software livre compatível com a GPL, mas que não tem a exigência de copyleft. É uma licença simples, suficiente para este projeto.

Referência: https://www.gnu.org/licenses/license-list.en.html#X11License
